/*
 * NxFs
 *
 * Simple file access APIs for the Entando Nx subsystem
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	nxsiteman "github.com/GIT_USER_ID/GIT_REPO_ID/server"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := nxsiteman.NewDefaultApiService()
	DefaultApiController := nxsiteman.NewDefaultApiController(DefaultApiService)

	router := nxsiteman.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
