/*
 * NxFs
 *
 * Simple file access APIs for the Entando Nx subsystem
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package controller

import (
	"context"
	"github.com/entando/entando-nxfs/server/model"
	"github.com/entando/entando-nxfs/server/net"
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	ApiNxfsBrowseEncodedPathGet(http.ResponseWriter, *http.Request)
	ApiNxfsObjectsEncodedPathDelete(http.ResponseWriter, *http.Request)
	ApiNxfsObjectsEncodedPathGet(http.ResponseWriter, *http.Request)
	ApiNxfsObjectsEncodedPathPublishPost(http.ResponseWriter, *http.Request)
	ApiNxfsObjectsEncodedPathPut(http.ResponseWriter, *http.Request)
	ApiNxfsObjectsEncodedPathUnpublishPost(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	ApiNxfsBrowseEncodedPathGet(context.Context, string, int32) (net.NxfsResponse, error)
	ApiNxfsObjectsEncodedPathDelete(context.Context, string) (net.NxfsResponse, error)
	ApiNxfsObjectsEncodedPathGet(context.Context, string) (net.NxfsResponse, error)
	ApiNxfsObjectsEncodedPathPublishPost(context.Context, string) (net.NxfsResponse, error)
	ApiNxfsObjectsEncodedPathPut(context.Context, string, model.FileObject) (net.NxfsResponse, error)
	ApiNxfsObjectsEncodedPathUnpublishPost(context.Context, string) (net.NxfsResponse, error)
}
