/*
 * NxFs
 *
 * Simple file access APIs for the Entando Nx subsystem
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nxsiteman

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"path"
	"path/filepath"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// ApiNxfsBrowseEncodedPathGet - Gets the list of objects in a directory
func (s *DefaultApiService) ApiNxfsBrowseEncodedPathGet(ctx context.Context, encodedPath string, maxdepth int32) (ImplResponse, error) {

	pathToBrowse, fileInfoToBrowse, errorResponse := composeFullPathOrErrorResponse(encodedPath)
	if errorResponse != nil {
		return *errorResponse, nil
	}

	// recursive function
	dirObjectArray, err := browseFileTree(pathToBrowse, fileInfoToBrowse, 0, maxdepth, []DirectoryObject{})
	if err != nil {
		return *ErrorResponse(http.StatusInternalServerError, "dir_listing_err", err.Error()), nil
	}

	return SuccessResponse(http.StatusOK, FlatDirectoryTree{dirObjectArray}), nil
}

// ApiNxfsObjectsEncodedPathDelete - Deletes an object
func (s *DefaultApiService) ApiNxfsObjectsEncodedPathDelete(ctx context.Context, encodedPath string) (ImplResponse, error) {

	pathToDelete, fileToDelete, errorResponse := composeFullPathOrErrorResponse(encodedPath)
	if errorResponse != nil {
		if errorResponse.Code == http.StatusNotFound {
			return SuccessResponse(http.StatusNoContent, nil), nil
		} else {
			return *errorResponse, nil
		}
	}
	absPathFile := path.Join(pathToDelete, fileToDelete.Name())

	if isDirWithChildren(absPathFile, fileToDelete) {
		return *ErrorResponse(http.StatusUnprocessableEntity, "dir_not_empty", "The folder to delete is not empty"), nil
	}

	if errorResponse = deleteFile(absPathFile); errorResponse != nil {
		return *errorResponse, nil
	}

	return SuccessResponse(http.StatusNoContent, nil), nil
}

// ApiNxfsObjectsEncodedPathGet - Gets an object
func (s *DefaultApiService) ApiNxfsObjectsEncodedPathGet(ctx context.Context, encodedPath string) (ImplResponse, error) {

	pathToBrowse, requestedFile, errorResponse := composeFullPathOrErrorResponse(encodedPath)
	if errorResponse != nil {
		return *errorResponse, nil
	}

	// if dir return error
	if requestedFile.IsDir() {
		return *ErrorResponse(http.StatusBadRequest, "dir_requested", "The received encoded path "+
			"corresponds to a directory. This endpoint returns files content, to browse a directory please use the browse one"), nil
	}

	// return file content
	fileContent, err := ioutil.ReadFile(path.Join(pathToBrowse, requestedFile.Name()))
	if err != nil {
		return *ErrorResponse(http.StatusBadRequest, "err_reading_content",
			fmt.Sprintf("An error occurred during the reading of the file content: %q", err.Error())), nil
	}

	// Convert []byte to string and print to screen
	fileContentString := string(fileContent)

	return SuccessResponse(http.StatusOK, toFileObject(pathToBrowse, requestedFile, fileContentString)), nil
}

// ApiNxfsObjectsEncodedPathPut - Creates or updates an object
func (s *DefaultApiService) ApiNxfsObjectsEncodedPathPut(ctx context.Context, encodedPath string, fileObject FileObject) (ImplResponse, error) {

	// dir can't have content
	if fileObject.Type == D && "" != fileObject.Content {
		return *ErrorResponse(http.StatusBadRequest, "full_content_for_dir", "A creation dir request can't contain a file content value"), nil
	} else if fileObject.Type == F && "" == fileObject.Content {
		// file must have content
		return *ErrorResponse(http.StatusBadRequest, "empty_content", "A file with empty content can't be saved"), nil
	}

	decodedPath, decodeErrResp := decodePath(encodedPath)
	if decodeErrResp != nil {
		return *decodeErrResp, nil
	}

	fullPathToSave := filepath.Join(GetBrowsableFsRootPath(), decodedPath)

	var creationErrResp *ImplResponse
	if fileObject.Type == D {
		creationErrResp = createDirectory(fullPathToSave)
	} else {
		creationErrResp = createFile(fullPathToSave, fileObject)
	}

	if creationErrResp != nil {
		return *creationErrResp, nil
	} else {
		return SuccessResponse(http.StatusCreated, toDirectoryObjectFromFilePath(fullPathToSave)), nil
	}
}

// ApiNxfsObjectsEncodedPathPublishPost - Publishes an object
func (s *DefaultApiService) ApiNxfsObjectsEncodedPathPublishPost(ctx context.Context, encodedPath string) (ImplResponse, error) {

	if errorResponse := publishPage(encodedPath); errorResponse != nil {
		return *errorResponse, nil
	} else {
		return SuccessResponse(http.StatusOK, nil), nil
	}
}

// ApiNxfsObjectsEncodedPathUnpublishPost - Publishes an object
func (s *DefaultApiService) ApiNxfsObjectsEncodedPathUnpublishPost(ctx context.Context, encodedPath string) (ImplResponse, error) {

	if errorResponse := unpublishPage(encodedPath); errorResponse != nil {
		return *errorResponse, nil
	} else {
		return SuccessResponse(http.StatusOK, nil), nil
	}
}
