/*
 * NxFs
 *
 * Simple file access APIs for the Entando Nx subsystem
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nxsiteman

// ObjectType : Type of object: - d: directory - f: file
type ObjectType string

// List of ObjectType
const (
	D ObjectType = "d"
	F ObjectType = "f"
)
