/*
 * NxFs
 *
 * Simple file access APIs for the Entando Nx subsystem
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package net

// NxfsResponse - NxfsResponse defines an error code with the associated body
type NxfsResponse struct {
	Code int
	Body interface{}
}
